language: python
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- "nightly"
install:
- pip install -U pip pytest
- pip install -e .[develop]
- pip install codecov
script:
- py.test --cov-report term-missing --cov-report xml:coverage.xml --cov
- ./pylint.sh
- codecov
deploy:
  provider: pypi
  user: lemmons
  password:
    secure: l1jWB+BjBf0/oGjK+9nOHnVp1/KF+J7V1+s5DVbdXHFzCIi/Et5xjuevttmmFDkJ3UUtbU1XrHm2wnPBrxocZqkpcP1DAUd3GD7A6b4C8AU65C7T1MgfXbLR5qGNYC+K59DqLVTV0jOM8GwZ7MiL1YIfSSkpmZn/l+BK397wMSMnl3DuIg6rse8Y3WVE+E0zDOsF5Mqs0CzvPcpSeHykG6LDHqSxR9ZT1verJq5Sj07OoF43ppllbaJ/EhcUVuN0Me5mJEPCtKb2qz8gcPF4THzBjec3wjZrD9NAsm5ewGQZGwydtL7SxVbzeTM6RlM7M3yYrvxD9H3YEo8HjqBLNTINZHLI9FLJ4dpHevGUuFzIbzpG4Ip6GbQgS1llGg5FS68pdnEZWP22igywKPOIM1qWsqrv8HSzcNJ7SXcUCpH2tmMrmEfHETI7UBRtYN3CGIn4glpaRDNoOsLp9W8zox7toJmJ+f+o5K2HWmXZcmcPxYCje+p0T0A/wyKlClVtFzHTFpcwwecCmmJ0AB0OUnRQp8oCbW2tHL7oHvQXZ/rUWA4r4es9DjUCHuORhc0ygGXBFAE0pna3O94xMXbPw07LxFwPKINU1RyWHWFx+ZLdWmpjSpJ7dTH/p2EfMXVyLXEUp0NPvkHJBqWxgYJgzr/OA7kD6q5RVRfXazxSjJI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    branch: master
    repo:  Lemmons/pytest-raises
