language: python
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- "nightly"
install:
- pip install -U pip pytest
- pip install -e .[develop]
- pip install codecov
script:
- py.test --cov-report term-missing --cov-report xml:coverage.xml --cov
- ./pylint.sh
- codecov
